---

# presets

defaults:

  - scope:
      path: ""
    values:
      origin: main
      read_time: 1 min
      php: "5.5"

  - scope:
      path: "/rules.html"
    values:
      origin: rules

  - scope:
      path: ""
      collection: faq
    values:
      origin: faq
      layout: default
      compass:
        up:
          title: "FAQ"
          path: /faq
          info: "Overview"

  - scope:
      path: "/articles"
    values:
      origin: articles

# collections

collections:
  faq:
    output: true
    output_ext: html
    permalink: /:path/


# maintenance

exclude:

  - README.md
  - Vagrantfile
  - assets/semantic-ui/gulpfile.js
  - assets/semantic-ui/src/
  - assets/semantic-ui/tasks/
  - assets/components/jquery/src/
  - assets/components/jquery/.bower.json
  - assets/components/jquery/bower.json
  - assets/components/jquery/MIT-LICENSE.txt
  - node_modules/
  - semantic.json

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

gems:
    - 'jekyll-sitemap'
    - 'jekyll-redirect-from'
